spring:
#  datasource: jdbc:h2:mem:db; DB_CLOSE_DELAY=-1
#  username: foo
#  password: bar

  minio:
    url: http://127.0.0.1:9000
    basketName: storage
    accessKey: minioadmin
    secretKey: minioadmin

  jwt:
    secret: 12345678qwertyui12345678qwertyui12345678qwertyui
    access_lifetime: 30m
    refresh_lifetime: 1d

  datasource:
    url: jdbc:postgresql://localhost:5432/forum-x-db
    username: postgres
    password: 1111

  flyway:
    enabled: true
    locations:
      - db.migration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

